# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c99757877269d08576bc20873378516e2fda0acd2d3b9846c5bcb3aa580d77c6c3ede066a9218f38e431ee10096b12427965b2d0c5ed2f01c98a4add43c266

test:
  secret_key_base: 3a0452b992842a2921dd58bd1508ffb82bdbbd403dc752c04b1eb3679103f298e32ac1173bb4dcb69128122c6f998a570fece03325930808abb84c3c79770e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
